image: ubuntu-gce-c

skip_tags: true

environment:
  PYTHON_VERSION: 3.12.6
  NDK_VERSION: r27
  GITHUB_TOKEN:
    secure: 9SKIwc3VSfYJ5IChvNR74rlTF9BMbAfhCGu1/TmYJBMtC6lkY+UDDkZNK7rC9xnQFUxMrNgoo9kNcNAbKbU8XAcrSwkP2H4mX04FI7P+YbxfiWC8nVHhGNxR4LzO+GO0

stack:
- python 3.12

install:
- read ver_maj ver_min < <(echo $PYTHON_VERSION | sed -E 's/^([0-9]+)\.([0-9]+).*/\1 \2/')
- export PYTHON_VERSION_SHORT="$ver_maj.$ver_min"

build_script:

# Build all Python ABIs
- ./build-all.sh $PYTHON_VERSION

# Package support package for use with mobile-forge
- mkdir -p dist
- tar -czf dist/python-android-mobile-forge-$PYTHON_VERSION_SHORT.tar.gz install support

# Package individual ABIs for use with serious_python Flutter package
- ./package-for-dart.sh install $PYTHON_VERSION arm64-v8a
- ./package-for-dart.sh install $PYTHON_VERSION armeabi-v7a
- ./package-for-dart.sh install $PYTHON_VERSION x86_64

# Push all archives to artifacts
- find dist -maxdepth 1 -type f -iname python-android-*.tar.gz -exec appveyor PushArtifact -DeploymentName python-android {} \;

test: off

deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  release: v$(PYTHON_VERSION_SHORT)
  artifact: python-android